In [4]:
import numpy as np
a = np.array([1,1,2,2])
b = a.reshape((2,2))
c = np.array([[3,3],[4,4]])
print(b)

[[1 1]
 [2 2]]


In [5]:
d = np.dot(b,c)
print(d)

[[ 7  7]
 [14 14]]


In [6]:
A = np.arange(2,14).reshape((3,4))
print(np.argmin(A))
print(np.argmax(A))

0
11


In [5]:
import pandas as pd
s = pd.Series([1,3,5,7,9])
print(s)

0    1
1    3
2    5
3    7
4    9
dtype: int64


In [3]:
import numpy as np
a = np.array([1,1,1])
b = np.array([2,2,2])

print(np.vstack((a,b)))
print(np.hstack((a,b)))


[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


In [7]:
import numpy as np
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
print(np.split(a, 2, axis = 1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [9]:
print(np.split(a, 3, axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [10]:
print(np.array_split(a, 3, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [11]:
import numpy as np

a = np.arange(4)

b = a
c = a
d = b

a[0] = 11
print(a)

[11  1  2  3]


In [12]:
b is a
c is a
d is a

True

In [13]:
d[1:3] = [22, 33]
print(a)
print(b)
print(c)

[11 22 33  3]
[11 22 33  3]
[11 22 33  3]


In [14]:
b = a.copy()
print(b)
a[3] = 44
print(a)
print(b)

[11 22 33  3]
[11 22 33 44]
[11 22 33  3]


In [5]:
import pandas as pd
import numpy as np
dates = pd.date_range('20180101',periods = 40)
# print(dates)
df = pd.DataFrame(np.random.randn(40,5),index=dates,columns=['a','b','c','d','e'])
# print(df)

In [6]:
df1 = pd.DataFrame(np.arange(12).reshape(3,4))
print(df1)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [7]:
df2 = pd.DataFrame({'A' : 1,
                   'B' : pd.Timestamp('20180101'),
                   'C' : pd.Series(1, index=list(range(4)), dtype='float32'),
                   'D' : np.array([3]*4, dtype='int32'),
                   'E' : pd.Categorical(['test', 'train', 'test', 'train']),
                   'F' : 'old'})
print(df2)

   A          B    C  D      E    F
0  1 2018-01-01  1.0  3   test  old
1  1 2018-01-01  1.0  3  train  old
2  1 2018-01-01  1.0  3   test  old
3  1 2018-01-01  1.0  3  train  old


In [8]:
dates = pd.date_range('20180101', periods = 6)
df = pd.DataFrame(np.arange(24).reshape((6, 4)), index = dates, columns= ['a','b', 'c', 'd'])
print(df)

             a   b   c   d
2018-01-01   0   1   2   3
2018-01-02   4   5   6   7
2018-01-03   8   9  10  11
2018-01-04  12  13  14  15
2018-01-05  16  17  18  19
2018-01-06  20  21  22  23


In [9]:
print(df.a)

2018-01-01     0
2018-01-02     4
2018-01-03     8
2018-01-04    12
2018-01-05    16
2018-01-06    20
Freq: D, Name: a, dtype: int64


In [12]:
print(df[0:3].a)

2018-01-01    0
2018-01-02    4
2018-01-03    8
Freq: D, Name: a, dtype: int64


In [13]:
print(df.loc['20180102'])

a    4
b    5
c    6
d    7
Name: 2018-01-02 00:00:00, dtype: int64


In [17]:
print(df.loc[:,['a', 'b']])

             a   b
2018-01-01   0   1
2018-01-02   4   5
2018-01-03   8   9
2018-01-04  12  13
2018-01-05  16  17
2018-01-06  20  21


In [21]:
print(df.loc['20180105':,['a', 'b']])

             a   b
2018-01-05  16  17
2018-01-06  20  21


In [22]:
print(df.iloc[3, 1])

13


In [23]:
print(df.iloc[3:5, 1:3])

             b   c
2018-01-04  13  14
2018-01-05  17  18


In [26]:
print(df.iloc[[1, 3, 5], 1:3])

             b   c
2018-01-02   5   6
2018-01-04  13  14
2018-01-06  21  22


In [27]:
print(df.ix[:3, ['a', 'c']])

            a   c
2018-01-01  0   2
2018-01-02  4   6
2018-01-03  8  10


/home/au/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [30]:
print(df[df.a>15])

             a   b   c   d
2018-01-05  16  17  18  19
2018-01-06  20  21  22  23


In [32]:
df.iloc[2,2] = 'asd'
df.loc['20180104', 'b'] = 1234
print(df)

             a     b    c   d
2018-01-01   0     1    2   3
2018-01-02   4     5    6   7
2018-01-03   8     9  asd  11
2018-01-04  12  1234   14  15
2018-01-05  16    17   18  19
2018-01-06  20    21   22  23


In [37]:
df.b[df.a>4] = 'ffff'

In [38]:
print(df)

             a     b    c   d
2018-01-01   0     1    2   3
2018-01-02   4     5    6   7
2018-01-03   8  ffff  asd  11
2018-01-04  12  ffff   14  15
2018-01-05  16  ffff   18  19
2018-01-06  20  ffff   22  23


In [43]:
df['g'] = pd.Series([1, 2, 3, 4, 5, 6], index = pd.date_range('20180101', periods=6))
print(df)

             a     b    c   d   f   e  g
2018-01-01   0     1    2   3 NaN NaN  1
2018-01-02   4     5    6   7 NaN NaN  2
2018-01-03   8  ffff  asd  11 NaN NaN  3
2018-01-04  12  ffff   14  15 NaN NaN  4
2018-01-05  16  ffff   18  19 NaN NaN  5
2018-01-06  20  ffff   22  23 NaN NaN  6
